from __future__ import annotations

from typing import Dict, List

GuideEntry = Dict[str, str]

PROVINCE_GUIDES: Dict[str, List[GuideEntry]] = {
    "กรุงเทพมหานคร": [
        {
            "name": "พระบรมมหาราชวัง",
            "english_name": "Grand Palace",
            "summary": "08:30 น. แต่งกายสุภาพเข้าชมพระแก้วมรกต",
            "map_url": "https://www.google.com/maps/place/Grand+Palace/@13.7500,100.4913,17z",
            "category": "สถานที่ศักดิ์สิทธิ์และประวัติศาสตร์",
            "history": "สร้างในรัชกาลที่ 1 ปี 2325 เป็นศูนย์กลางราชอาณาจักร",
            "activity": "ชมพระแก้วมรกตและพระที่นั่งจักรี",
            "hours": "08:30-15:30 น.",
            "budget": "500-800 บาท รวมค่าเข้าชม",
        },
        {
            "name": "สวนลุมพินี",
            "english_name": "Lumpini Park",
            "summary": "เช้าเดินหรือวิ่งกลางสวนร่มรื่น",
            "map_url": "https://www.google.com/maps/place/Lumphini+Park/@13.7300,100.5410,16z",
            "category": "สถานที่ท่องเที่ยวทางธรรมชาติ",
            "history": "สวนสาธารณะแรกของไทย ก่อตั้ง พ.ศ. 2468 ในรัชกาลที่ 6",
            "activity": "วิ่ง ยืดเส้น หรือพายเรือ",
            "hours": "04:30-21:00 น.",
            "budget": "ฟรี",
        },
        {
            "name": "ตลาดน้อย",
            "english_name": "Talad Noi",
            "summary": "บ่ายเดินชมสตรีทอาร์ตและชิมกาแฟ",
            "map_url": "https://www.google.com/maps/place/Talad+Noi/@13.7379,100.5138,17z",
            "category": "ตลาดชุมชนวัฒนธรรม",
            "history": "ชุมชนจีนริมน้ำเก่าแก่ตั้งแต่สมัยรัชกาลที่ 4",
            "activity": "เดินชมโกดังโบราณและจิบกาแฟ",
            "hours": "10:00-20:00 น.",
            "budget": "150-400 บาท",
        },
        {
            "name": "พิพิธภัณฑสถานแห่งชาติ พระนคร",
            "english_name": "Bangkok National Museum",
            "summary": "บ่ายสำรวจโบราณวัตถุและราชรถโบราณ",
            "map_url": "https://www.google.com/maps/place/Bangkok+National+Museum/@13.7576,100.4924,18z",
            "category": "พิพิธภัณฑ์อุทยานประวัติศาสตร์",
            "history": "พิพิธภัณฑ์แห่งชาติที่ใหญ่ที่สุดของไทย เปิดปี 2471",
            "activity": "เดินชมราชรถและศิลปะสมัยต่าง ๆ",
            "hours": "09:00-16:00 น. (ปิดจันทร์-อังคาร)",
            "budget": "30-200 บาท",
        },
        {
            "name": "ซอยเจริญกรุง 44",
            "english_name": "Charoen Krung 44 Alley",
            "summary": "เย็นจิบกาแฟสโลว์บาร์ชมศิลป์ชุมชน",
            "map_url": "https://www.google.com/maps/place/Charoen+Krung+44/@13.7239,100.5149,18z",
            "category": "กิจกรรมไลฟ์สไตล์และคาเฟ่",
            "history": "อยู่บนถนนยุคแรกของกรุงเทพฯ ที่สร้าง พ.ศ. 2407",
            "activity": "เดินชมแกลเลอรีและคาเฟ่",
            "hours": "10:00-20:00 น.",
            "budget": "150-350 บาท",
        },
    ],
    "สมุทรสงคราม": [
        {
            "name": "วัดบางกุ้ง",
            "english_name": "Bang Kung Temple",
            "summary": "เช้ากราบหลวงพ่อในโบสถ์รากไทร",
            "map_url": "https://www.google.com/maps/place/Wat+Bang+Kung/@13.4020,99.9685,18z",
            "category": "สถานที่ศักดิ์สิทธิ์และประวัติศาสตร์",
            "history": "โบสถ์สร้างราว พ.ศ. 2317 ปกคลุมด้วยรากไทรยุคปลายอยุธยา",
            "activity": "สักการะหลวงพ่อและชมโบสถ์รากไม้",
            "hours": "08:00-17:00 น.",
            "budget": "ฟรี",
        },
        {
            "name": "คลองโคน",
            "english_name": "Khlong Khon Mangrove",
            "summary": "สายล่องเรือชมป่าชายเลนและนาก",
            "map_url": "https://www.google.com/maps/place/Khlong+Khon+Mangrove/@13.3650,99.9380,15z",
            "category": "สถานที่ท่องเที่ยวทางธรรมชาติ",
            "history": "ชุมชนประมงพื้นบ้านอนุรักษ์ป่าชายเลนมากว่า 40 ปี",
            "activity": "ปลูกป่าชายเลนและชิมปูทะเลสด",
            "hours": "08:00-17:00 น.",
            "budget": "500-900 บาท",
        },
        {
            "name": "ตลาดน้ำอัมพวา",
            "english_name": "Amphawa Floating Market",
            "summary": "เย็นเดินตลาดริมน้ำและล่องเรือดูหิ่งห้อย",
            "map_url": "https://www.google.com/maps/place/Amphawa+Floating+Market/@13.4325,99.9553,17z",
            "category": "ตลาดชุมชนวัฒนธรรม",
            "history": "ตลาดริมน้ำเก่าแก่ตั้งแต่สมัยอยุธยา บ้านเกิดพระเจ้าตากสิน",
            "activity": "ล่องเรือ กินอาหารพื้นบ้าน",
            "hours": "ศุกร์-อาทิตย์ 16:00-21:00 น.",
            "budget": "200-500 บาท",
        },
        {
            "name": "อุทยาน ร.2",
            "english_name": "King Rama II Memorial Park",
            "summary": "บ่ายชมสวนและเรือนไทยโบราณ",
            "map_url": "https://www.google.com/maps/place/King+Rama+II+Memorial+Park/@13.4305,99.9534,18z",
            "category": "พิพิธภัณฑ์อุทยานประวัติศาสตร์",
            "history": "อุทยานเฉลิมพระเกียรติรัชกาลที่ 2 สร้างปี 2525",
            "activity": "เดินเรือนไทย ชมพิพิธภัณฑ์",
            "hours": "08:30-17:00 น.",
            "budget": "30-60 บาท",
        },
        {
            "name": "บ้านดำเนินสะดวก",
            "english_name": "Damnoen Saduak Village",
            "summary": "เย็นล่องเรือคุยกับชาวสวน",
            "map_url": "https://www.google.com/maps/place/Damnoen+Saduak/@13.5176,99.9599,16z",
            "category": "กิจกรรมไลฟ์สไตล์และคาเฟ่",
            "history": "ชุมชนชาวสวนริมคลองดำเนินสะดวก ขุดเมื่อรัชกาลที่ 4",
            "activity": "พายเรือ ซื้อผลไม้จากชาวสวน",
            "hours": "06:00-12:00 น.",
            "budget": "300-600 บาท",
        },
    ],
    "เชียงใหม่": [
        {
            "name": "วัดพระธาตุดอยสุเทพ",
            "english_name": "Wat Phra That Doi Suthep",
            "summary": "ตีห้าขึ้นรถแดงไหว้พระชมวิวเมือง",
            "map_url": "https://www.google.com/maps/place/Wat+Phra+That+Doi+Suthep/@18.8049,98.9216,17z",
            "category": "สถานที่ศักดิ์สิทธิ์และประวัติศาสตร์",
            "history": "สร้างปี 1929 เพื่อบรรจุพระบรมสารีริกธาตุ",
            "activity": "ขึ้นกระเช้าหรือเดินบันได 306 ขั้น",
            "hours": "05:30-19:30 น.",
            "budget": "30-100 บาท",
        },
        {
            "name": "แม่กำปอง",
            "english_name": "Mae Kampong Village",
            "summary": "สายๆ จิบชาเขียวบนระเบียงไม้",
            "map_url": "https://www.google.com/maps/place/Mae+Kampong/@18.8685,99.3611,15z",
            "category": "สถานที่ท่องเที่ยวทางธรรมชาติ",
            "history": "หมู่บ้านชาวไทยใหญ่ก่อตั้งกว่า 100 ปี ทำไร่ชาและกาแฟ",
            "activity": "เดินเล่นคาเฟ่ ชมลำธาร",
            "hours": "09:00-17:00 น.",
            "budget": "200-500 บาท",
        },
        {
            "name": "ถนนคนเดินท่าแพ",
            "english_name": "Tha Phae Walking Street",
            "summary": "ค่ำเดินเลือกสินค้างานคราฟต์",
            "map_url": "https://www.google.com/maps/place/Tha+Phae+Walking+Street/@18.7878,99.0015,17z",
            "category": "ตลาดชุมชนวัฒนธรรม",
            "history": "ถนนคนเดินใหญ่สุดของเชียงใหม่ เริ่มจัดปี 2545",
            "activity": "สัมผัสดนตรีสดและถนนสายอาหาร",
            "hours": "อาทิตย์ 16:00-22:00 น.",
            "budget": "100-400 บาท",
        },
        {
            "name": "พิพิธภัณฑ์พื้นบ้านล้านนา",
            "english_name": "Lanna Folklife Museum",
            "summary": "บ่ายชมวิถีล้านนาในตึกขาวอาร์ตเดโค",
            "map_url": "https://www.google.com/maps/place/Lanna+Folklife+Museum/@18.7870,98.9938,18z",
            "category": "พิพิธภัณฑ์อุทยานประวัติศาสตร์",
            "history": "อาคารศาลาเก่าเชียงใหม่ ปรับเป็นพิพิธภัณฑ์ปี 2556",
            "activity": "ชมชุดพื้นเมืองและของใช้โบราณ",
            "hours": "08:30-17:00 น.",
            "budget": "90-180 บาท",
        },
        {
            "name": "ถนนนิมมาน",
            "english_name": "Nimman Road",
            "summary": "ค่ำชิมไอศกรีมโฮมเมดเดินเล่นชิล",
            "map_url": "https://www.google.com/maps/place/Nimmanahaeminda+Road/@18.7996,98.9698,16z",
            "category": "กิจกรรมไลฟ์สไตล์และคาเฟ่",
            "history": "ย่านที่พักนักศึกษาในยุค 1980 กลายเป็นแหล่งคาเฟ่และแกลเลอรี",
            "activity": "คาเฟ่ฮอปปิ้งและบาร์",
            "hours": "10:00-23:00 น.",
            "budget": "200-500 บาท",
        },
    ],
    "ภูเก็ต": [
        {
            "name": "พระใหญ่ภูเก็ต",
            "english_name": "Phuket Big Buddha",
            "summary": "เช้ากราบพระใหญ่และชมวิวทะเล",
            "map_url": "https://www.google.com/maps/place/Big+Buddha+Phuket/@7.8276,98.3128,17z",
            "category": "สถานที่ศักดิ์สิทธิ์และประวัติศาสตร์",
            "history": "สร้างปี 2545 สูง 45 เมตร ปูด้วยหินอ่อนพม่า",
            "activity": "ไหว้พระและชมวิว 360 องศา",
            "hours": "06:00-19:00 น.",
            "budget": "บริจาคตามศรัทธา",
        },
        {
            "name": "หาดกะตะ",
            "english_name": "Kata Beach",
            "summary": "สายเล่นเซิร์ฟบนผืนทรายโค้ง",
            "map_url": "https://www.google.com/maps/place/Kata+Beach/@7.8210,98.2968,15z",
            "category": "สถานที่ท่องเที่ยวทางธรรมชาติ",
            "history": "ชายหาดชุมชนประมงที่เริ่มเป็นแหล่งท่องเที่ยวตั้งแต่ทศวรรษ 1970",
            "activity": "โต้คลื่นและเล่นบอดี้บอร์ด",
            "hours": "06:00-18:30 น.",
            "budget": "300-700 บาท (ค่าเช่าอุปกรณ์)",
        },
        {
            "name": "หลาดปล่อยของ",
            "english_name": "Chillva Market",
            "summary": "ค่ำเดินตลาดคอนเทนเนอร์สีสด",
            "map_url": "https://www.google.com/maps/place/Chillva+Market/@7.9045,98.3684,17z",
            "category": "ตลาดชุมชนวัฒนธรรม",
            "history": "ตลาดไนท์มาร์เก็ตคนภูเก็ต เปิดปี 2559",
            "activity": "ช้อปสินค้าไลฟ์สไตล์และชิมอาหาร",
            "hours": "พุธ-เสาร์ 17:00-22:00 น.",
            "budget": "200-400 บาท",
        },
        {
            "name": "พิพิธภัณฑ์เหมืองแร่ภูเก็ต",
            "english_name": "Phuket Mining Museum",
            "summary": "บ่ายเรียนรู้ประวัติอุตสาหกรรมดีบุก",
            "map_url": "https://www.google.com/maps/place/Phuket+Mining+Museum/@7.9326,98.3587,17z",
            "category": "พิพิธภัณฑ์อุทยานประวัติศาสตร์",
            "history": "จัดแสดงชีวิตเหมืองดีบุกยุคเฟื่องฟูในทศวรรษ 1930",
            "activity": "ชมอาคารเหมืองจำลองและเครื่องมือโบราณ",
            "hours": "09:00-16:00 น. (ปิดวันจันทร์)",
            "budget": "100-200 บาท",
        },
        {
            "name": "ย่านเมืองเก่าภูเก็ต",
            "english_name": "Phuket Old Town",
            "summary": "เย็นถ่ายภาพตึกชิโนโปรตุกีสและคาเฟ่",
            "map_url": "https://www.google.com/maps/place/Phuket+Old+Town/@7.8845,98.3900,16z",
            "category": "กิจกรรมไลฟ์สไตล์และคาเฟ่",
            "history": "ตึกชิโน-โปรตุกีสปลายศตวรรษที่ 19 จากยุคเหมืองดีบุก",
            "activity": "ถ่ายภาพตึกสวยและชิมขนมโบราณ",
            "hours": "09:00-20:00 น.",
            "budget": "200-400 บาท",
        },
    ],
    "ขอนแก่น": [],
    "แม่ฮ่องสอน": [],
}

PROVINCE_SYNONYMS: Dict[str, List[str]] = {
    "กรุงเทพมหานคร": ["กรุงเทพ", "bangkok", "bkk", "krung thep", "krungthep"],
    "สมุทรสงคราม": ["อัมพวา", "amphawa", "mae klong", "maeklong"],
    "เชียงใหม่": ["chiangmai", "chiang mai"],
    "ภูเก็ต": ["phuket"],
    "ขอนแก่น": ["khon kaen", "ขอนแกน"],
    "แม่ฮ่องสอน": ["mae hong son", "แม่ฮ้องสอน"],
}
